import type { ImageSourcePropType, ViewStyle } from 'react-native';

export type ThemeMode = 'auto' | 'dark' | 'light';
export type GlassStyle = 'liquid' | 'frosted' | 'clear' | 'solid';
export type IconShape = 'circle' | 'squircle' | 'rounded' | 'square' | 'teardrop';
export type ClockFace =
  | 'large'
  | 'bold'
  | 'stacked'
  | 'minimal'
  | 'divider'
  | 'giant'
  | 'stencil'
  | 'condensed'
  | 'rounded'
  | 'digital'
  | 'retro';
/** @deprecated kept for older saved settings */
export type ClockStyle = ClockFace;
export type DrawerStyle = 'grid' | 'pages' | 'list';
export type SwipeDownAction = 'controls' | 'split' | 'notifications';
export type EdgeHandle = 'upper' | 'middle' | 'lower';

export type Settings = {
  theme: ThemeMode;
  glass: GlassStyle;
  /** Hex color, or 'wallpaper' to follow the system wallpaper. */
  accent: string;
  /** 'system' (phone wallpaper), a key of GRADIENTS, 'img:<id>' (theme art) or 'photo'. */
  wallpaper: string;
  /** file:// URI of the user's photo wallpaper (when wallpaper === 'photo'). */
  photoUri: string | null;
  /** Blur radius for picture wallpapers on the home screen (0 = sharp). */
  wallpaperBlur: number;
  /** Frosted (blurred-wallpaper) backgrounds behind the drawer and panels. */
  panelBlur: boolean;
  dim: number;
  iconShape: IconShape;
  iconSize: number;
  columns: number;
  showLabels: boolean;
  themedIcons: boolean;
  iconShine: boolean;
  /** Soft light reflection along the top edge of glass boxes. */
  glassEdge: boolean;
  clockStyle: ClockFace;
  /** 'auto', 'accent' or a hex color. */
  clockColor: string;
  clock24h: boolean;
  showClock: boolean;
  showGlance: boolean;
  showSearch: boolean;
  swipeDown: SwipeDownAction;
  drawerStyle: DrawerStyle;
  azScroller: boolean;
  drawerCategories: boolean;
  showFrequent: boolean;
  edgePanel: boolean;
  edgeHandle: EdgeHandle;
  /** Edge bar over other apps too (needs "Display over other apps"). */
  edgeOverlay: boolean;
  /** Clipboard history in the edge panel (+ Share → "Lumo clipboard"). */
  clipboard: boolean;
  /** Hours unpinned clipboard items are kept; 0 = until removed. */
  clipboardKeep: number;
  lockEnabled: boolean;
  lockFace: ClockFace;
  lockColor: string;
  lockShortcuts: boolean;
  themeId: string | null;
};

export const DEFAULT_SETTINGS: Settings = {
  theme: 'dark',
  glass: 'liquid',
  accent: '#0A84FF',
  wallpaper: 'system',
  photoUri: null,
  wallpaperBlur: 0,
  panelBlur: true,
  dim: 0.15,
  iconShape: 'squircle',
  iconSize: 56,
  columns: 4,
  showLabels: true,
  themedIcons: false,
  iconShine: true,
  glassEdge: true,
  clockStyle: 'large',
  clockColor: 'auto',
  clock24h: false,
  showClock: true,
  showGlance: true,
  showSearch: true,
  swipeDown: 'controls',
  drawerStyle: 'grid',
  azScroller: true,
  drawerCategories: true,
  showFrequent: true,
  edgePanel: true,
  edgeHandle: 'upper',
  edgeOverlay: false,
  clipboard: true,
  clipboardKeep: 24,
  lockEnabled: false,
  lockFace: 'condensed',
  lockColor: 'auto',
  lockShortcuts: true,
  themeId: null,
};

export const ACCENTS = [
  '#0A84FF',
  '#5E5CE6',
  '#BF5AF2',
  '#FF375F',
  '#FF9F0A',
  '#FFD60A',
  '#30D158',
  '#64D2FF',
];

export type Gradient = { name: string; colors: [string, string, ...string[]]; light?: boolean };

export const GRADIENTS: Record<string, Gradient> = {
  midnight: { name: 'Midnight', colors: ['#0B1026', '#2B1B5A', '#5A2A82'] },
  aurora: { name: 'Aurora', colors: ['#03252B', '#0B6E6E', '#58C6A0'] },
  sunset: { name: 'Sunset', colors: ['#2E1437', '#8E2D5A', '#F28B50'] },
  ocean: { name: 'Ocean', colors: ['#071A35', '#1F5F8B', '#53A7D8'] },
  rose: { name: 'Rose', colors: ['#2A1225', '#A4508B', '#F3A4B5'] },
  graphite: { name: 'Graphite', colors: ['#0B0B0D', '#1C1C22', '#34343E'] },
  dawn: { name: 'Dawn', colors: ['#FBD3E9', '#E2ECF9', '#BBD2F5'], light: true },
  lilac: { name: 'Lilac', colors: ['#E0C3FC', '#C2D6FD', '#8EC5FC'], light: true },
};

/** Theme art generated by scripts/generate-wallpapers.mjs (soft, so it upscales and blurs well). */
export const WALLPAPER_IMAGES: Record<string, { name: string; source: ImageSourcePropType; light: boolean }> = {
  colorful: { name: 'Colorful', source: require('../assets/wallpapers/colorful.jpg'), light: true },
  seek: { name: 'Seek', source: require('../assets/wallpapers/seek.jpg'), light: true },
  aurora: { name: 'Aurora', source: require('../assets/wallpapers/aurora.jpg'), light: false },
  sunset: { name: 'Sunset', source: require('../assets/wallpapers/sunset.jpg'), light: false },
  mint: { name: 'Mint', source: require('../assets/wallpapers/mint.jpg'), light: true },
  midnight: { name: 'Midnight', source: require('../assets/wallpapers/midnight.jpg'), light: false },
  blossom: { name: 'Blossom', source: require('../assets/wallpapers/blossom.jpg'), light: true },
  court: { name: 'Court', source: require('../assets/wallpapers/court.jpg'), light: false },
};

/** The picture behind the home screen, or null for the phone wallpaper / gradients. */
export function wallpaperImage(settings: Pick<Settings, 'wallpaper' | 'photoUri'>): ImageSourcePropType | null {
  if (settings.wallpaper === 'photo') return settings.photoUri ? { uri: settings.photoUri } : null;
  if (settings.wallpaper.startsWith('img:')) return WALLPAPER_IMAGES[settings.wallpaper.slice(4)]?.source ?? null;
  return null;
}

export const CLOCK_FACES: { key: ClockFace; name: string }[] = [
  { key: 'large', name: 'Thin' },
  { key: 'condensed', name: 'Tall' },
  { key: 'divider', name: 'Divider' },
  { key: 'giant', name: 'Giant' },
  { key: 'rounded', name: 'Rounded' },
  { key: 'stencil', name: 'Stencil' },
  { key: 'bold', name: 'Bold' },
  { key: 'stacked', name: 'Stacked' },
  { key: 'digital', name: 'Digital' },
  { key: 'retro', name: 'Retro' },
  { key: 'minimal', name: 'Card' },
];

export const CLOCK_COLORS = ['auto', 'accent', '#FFFFFF', '#FFE8A3', '#FFB3C7', '#A8E6FF', '#C3F584', '#1C1C1E'];

export type ThemePreset = {
  id: string;
  name: string;
  subtitle: string;
  patch: Partial<Settings>;
};

/** One-tap looks: wallpaper + colors + glass + icons + clocks. */
export const THEMES: ThemePreset[] = [
  {
    id: 'colorful',
    name: 'Colorful',
    subtitle: 'Bright & playful',
    patch: {
      wallpaper: 'img:colorful', theme: 'light', glass: 'liquid', accent: '#FF8A00', iconShape: 'squircle',
      clockStyle: 'rounded', clockColor: '#FFFFFF', lockFace: 'rounded', lockColor: '#FFFFFF', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'seek',
    name: 'Seek',
    subtitle: 'Light · calm waves',
    patch: {
      wallpaper: 'img:seek', theme: 'light', glass: 'frosted', accent: '#0FA3B8', iconShape: 'rounded',
      clockStyle: 'large', clockColor: '#FFFFFF', lockFace: 'giant', lockColor: '#FFFFFF', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    subtitle: 'Northern lights',
    patch: {
      wallpaper: 'img:aurora', theme: 'dark', glass: 'liquid', accent: '#3BF5B0', iconShape: 'squircle',
      clockStyle: 'condensed', clockColor: '#FFFFFF', lockFace: 'condensed', lockColor: '#B7FFE3', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    subtitle: 'Warm glow',
    patch: {
      wallpaper: 'img:sunset', theme: 'dark', glass: 'liquid', accent: '#FF9F45', iconShape: 'circle',
      clockStyle: 'giant', clockColor: '#FFE8A3', lockFace: 'giant', lockColor: '#FFE8A3', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    subtitle: 'Fresh pastel',
    patch: {
      wallpaper: 'img:mint', theme: 'light', glass: 'frosted', accent: '#16A34A', iconShape: 'squircle',
      clockStyle: 'divider', clockColor: 'auto', lockFace: 'divider', lockColor: 'auto', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    subtitle: 'Deep & glassy',
    patch: {
      wallpaper: 'img:midnight', theme: 'dark', glass: 'clear', accent: '#5E5CE6', iconShape: 'rounded',
      clockStyle: 'digital', clockColor: '#A8E6FF', lockFace: 'digital', lockColor: '#A8E6FF', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'blossom',
    name: 'Blossom',
    subtitle: 'Soft pink',
    patch: {
      wallpaper: 'img:blossom', theme: 'light', glass: 'liquid', accent: '#FF2D78', iconShape: 'teardrop',
      clockStyle: 'retro', clockColor: '#FF2D78', lockFace: 'retro', lockColor: '#FF2D78', dim: 0, wallpaperBlur: 0,
    },
  },
  {
    id: 'court',
    name: 'Court',
    subtitle: 'Sporty stencil',
    patch: {
      wallpaper: 'img:court', theme: 'dark', glass: 'liquid', accent: '#FF7EB6', iconShape: 'circle',
      clockStyle: 'stencil', clockColor: '#FFFFFF', lockFace: 'stencil', lockColor: '#FFFFFF', dim: 0, wallpaperBlur: 0,
    },
  },
];

export const SHAPES: { key: IconShape; name: string }[] = [
  { key: 'squircle', name: 'Squircle' },
  { key: 'circle', name: 'Circle' },
  { key: 'rounded', name: 'Rounded' },
  { key: 'teardrop', name: 'Teardrop' },
  { key: 'square', name: 'Square' },
];

export function shapeStyle(shape: IconShape, size: number): ViewStyle {
  switch (shape) {
    case 'circle':
      return { borderRadius: size / 2 };
    case 'rounded':
      return { borderRadius: size * 0.22 };
    case 'square':
      return { borderRadius: size * 0.08 };
    case 'teardrop':
      return {
        borderTopLeftRadius: size / 2,
        borderTopRightRadius: size / 2,
        borderBottomLeftRadius: size / 2,
        borderBottomRightRadius: size * 0.16,
      };
    case 'squircle':
    default:
      return { borderRadius: size * 0.32 };
  }
}

function parseHex(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h.padEnd(6, '0');
  const n = parseInt(full.slice(0, 6), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

export function mix(a: string, b: string, amount: number): string {
  const ca = parseHex(a);
  const cb = parseHex(b);
  const out = ca.map((v, i) => Math.round(v + (cb[i] - v) * amount));
  return '#' + out.map((v) => v.toString(16).padStart(2, '0')).join('');
}

export function withAlpha(hex: string, alpha: number): string {
  const [r, g, b] = parseHex(hex);
  return `rgba(${r},${g},${b},${alpha})`;
}

export type Palette = {
  dark: boolean;
  accent: string;
  text: string;
  subtext: string;
  /** Text drawn straight onto the wallpaper. */
  onWallpaper: string;
  glassBg: string;
  glassBorder: string;
  glassSheen: [string, string, ...string[]];
  glassHighlight: string;
  sheetBg: string;
  separator: string;
  chipBg: string;
  themedIconBg: string;
  themedIconFg: string;
};

export function makePalette(dark: boolean, glass: GlassStyle, accent: string): Palette {
  const base = {
    dark,
    accent,
    text: dark ? '#FFFFFF' : '#111114',
    subtext: dark ? 'rgba(235,235,245,0.62)' : 'rgba(60,60,67,0.7)',
    onWallpaper: dark ? '#FFFFFF' : '#0E0E12',
    separator: dark ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.08)',
    chipBg: dark ? 'rgba(255,255,255,0.10)' : 'rgba(0,0,0,0.06)',
    sheetBg: dark ? 'rgba(18,18,24,0.94)' : 'rgba(246,246,250,0.96)',
    themedIconBg: dark ? mix(accent, '#000000', 0.72) : mix(accent, '#FFFFFF', 0.82),
    themedIconFg: dark ? mix(accent, '#FFFFFF', 0.55) : mix(accent, '#000000', 0.4),
  };

  switch (glass) {
    case 'frosted':
      return {
        ...base,
        glassBg: dark ? 'rgba(30,30,38,0.62)' : 'rgba(255,255,255,0.72)',
        glassBorder: dark ? 'rgba(255,255,255,0.14)' : 'rgba(255,255,255,0.9)',
        glassSheen: ['rgba(255,255,255,0.14)', 'rgba(255,255,255,0.02)'],
        glassHighlight: 'rgba(255,255,255,0.25)',
      };
    case 'clear':
      return {
        ...base,
        glassBg: dark ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.18)',
        glassBorder: dark ? 'rgba(255,255,255,0.32)' : 'rgba(255,255,255,0.8)',
        glassSheen: ['rgba(255,255,255,0.22)', 'rgba(255,255,255,0.0)', 'rgba(255,255,255,0.0)', 'rgba(255,255,255,0.12)'],
        glassHighlight: 'rgba(255,255,255,0.7)',
      };
    case 'solid':
      return {
        ...base,
        glassBg: dark ? '#1C1C22' : '#FFFFFF',
        glassBorder: dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
        glassSheen: ['rgba(255,255,255,0)', 'rgba(255,255,255,0)'],
        glassHighlight: 'rgba(255,255,255,0)',
      };
    case 'liquid':
    default:
      return {
        ...base,
        glassBg: dark ? 'rgba(24,24,34,0.30)' : 'rgba(255,255,255,0.40)',
        glassBorder: dark ? 'rgba(255,255,255,0.24)' : 'rgba(255,255,255,0.75)',
        glassSheen: [
          'rgba(255,255,255,0.30)',
          'rgba(255,255,255,0.07)',
          'rgba(255,255,255,0.0)',
          'rgba(255,255,255,0.14)',
        ],
        glassHighlight: 'rgba(255,255,255,0.65)',
      };
  }
}

export const CATEGORIES: { key: string; name: string; match: (c: number) => boolean }[] = [
  { key: 'social', name: 'Social', match: (c) => c === 4 },
  { key: 'media', name: 'Media', match: (c) => c === 1 || c === 2 || c === 3 },
  { key: 'games', name: 'Games', match: (c) => c === 0 },
  { key: 'work', name: 'Productivity', match: (c) => c === 7 },
  { key: 'travel', name: 'News & Maps', match: (c) => c === 5 || c === 6 },
  { key: 'other', name: 'Other', match: (c) => c < 0 || c > 7 },
];
